--- 
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "shyam_ansible_keypair"
      # vpc_subnet_id: subnet-013744e41e8088axx
      instance_type: t2.micro
      security_group: default
      region: ap-south-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
    loop:
     - { image: "ami-0a1235697f4afa8a4" , name: "ansible-instance-1" }
     - { image: "ami-0f918f7e67a3323f0" , name: "ansible-instance-2" }
     - { image: "ami-0a1235697f4afa8a4" , name: "ansible-instance-3" }
